# Default values for RaftTimeDB Helm chart

replicas: 3

image:
  repository: ghcr.io/nodenestor/rafttimedb
  tag: latest
  pullPolicy: IfNotPresent

spacetimedb:
  image: clockworklabs/spacetime
  tag: latest
  storage: 10Gi
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "2"
      memory: 4Gi

rafttimedb:
  clientPort: 3001
  raftPort: 4001
  storage: 1Gi
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: "1"
      memory: 512Mi

service:
  type: LoadBalancer
  port: 3001
